# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Corbett's
tagline:             'course of life'
description:         ''
url:                 http://localhost:4001
baseurl:             ''

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Build settings
exclude: ["README.md"]
sass:
  style: compressed
